name: open-witness
version: "0.7"
author: Ashley Yakeley
copyright: (c) 2017-2024 Ashley Yakeley
license: BSD-2-Clause
license-file: LICENSE
maintainer: <ashley@semantic.org>
github: "AshleyYakeley/open-witness"

category: Data
synopsis: open witnesses
description:
    Open witnesses are witnesses that can witness to any type. However, they cannot be constructed, they can only be generated in the IO monad.
    See the 2008 draft paper /Witnesses and Open Witnesses/ (<https://semantic.org/wp-content/uploads/Open-Witnesses.pdf>).

tested-with:
- "GHC == 9.8.4"
- "GHC == 9.10.1"

extra-doc-files:
- changelog.md

language: GHC2021
default-extensions:
- AllowAmbiguousTypes
- Arrows
- DataKinds
- DefaultSignatures
- DerivingStrategies
- FunctionalDependencies
- ImplicitParams
- NoImplicitPrelude
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- QuantifiedConstraints
- RecordWildCards
- RecursiveDo
- RoleAnnotations
- NoStarIsType
- TemplateHaskell
- TypeAbstractions
- TypeFamilies
- TypeFamilyDependencies
- UndecidableInstances
- UndecidableSuperClasses
- ViewPatterns
ghc-options:
- -Weverything
- -Wno-missing-import-lists
- -Wno-missing-export-lists
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
- -Wno-missing-kind-signatures
- -Wno-partial-type-signatures
- -Wno-missing-role-annotations
- -Wno-monomorphism-restriction
- -Wno-missing-local-signatures
- -Wno-partial-fields
- -Wno-all-missed-specialisations # non-breaking
- -Wno-missed-specialisations # non-breaking

library:
    source-dirs: src
    dependencies:
    - base >= 4.19 && < 5
    - random >= 1.2
    - template-haskell >= 2.17
    - transformers >= 0.5
    - hashable >= 1.3
    - constraints >= 0.14
    - witness >= 0.7
    exposed-modules:
    - Data.Type.OpenWitness
    - Data.Type.OpenWitness.TypeRep
    - Data.Type.OpenWitness.Typeable
    - Data.Type.OpenWitness.Dynamic
    - Data.Type.OpenWitness.Exception
    - Data.Type.OpenWitness.ST
    - Data.Type.OpenWitness.Instance
    - Data.Type.OpenWitness.Witnessed
    other-modules: []

tests:
    tests:
        source-dirs: test
        dependencies:
        - base >= 4.19 && < 5
        - witness
        - open-witness
        - tasty
        - tasty-hunit
        main: Main.hs
        other-modules:
        - Object
