name: open-witness
version: "0.4.0.1"
author: Ashley Yakeley
copyright: (c) 2017-2019 Ashley Yakeley
license: BSD3
license-file: LICENSE
maintainer: <ashley@semantic.org>
homepage: https://github.com/AshleyYakeley/open-witness
bug-reports: https://github.com/AshleyYakeley/open-witness/issues
synopsis: open witnesses
description:
    Open witnesses are witnesses that can witness to any type. However, they cannot be constructed, they can only be generated in the IO monad.
    See the paper /Witnesses and Open Witnesses/ (<http://semantic.org/stuff/Open-Witnesses.pdf>).
category: Data
build-type: Simple

library:
    source-dirs: src
    default-extensions:
      - AllowAmbiguousTypes
      - Arrows
      - ConstraintKinds
      - DataKinds
      - DefaultSignatures
      - EmptyCase
      - EmptyDataDecls
      - ExistentialQuantification
      - FlexibleContexts
      - FlexibleInstances
      - ForeignFunctionInterface
      - FunctionalDependencies
      - GADTs
      - GeneralizedNewtypeDeriving
      - ImplicitParams
      - NoImplicitPrelude
      - InstanceSigs
      - KindSignatures
      - LambdaCase
      - MonadFailDesugaring
      - MultiParamTypeClasses
      - OverloadedLabels
      - OverloadedStrings
      - PartialTypeSignatures
      - PatternGuards
      - PatternSynonyms
      - PolyKinds
      - RankNTypes
      - RecordWildCards
      - RecursiveDo
      - ScopedTypeVariables
      - StandaloneDeriving
      - NoStarIsType
      - TemplateHaskell
      - TypeApplications
      - TypeFamilies
      - TypeFamilyDependencies
      - TypeInType
      - TypeOperators
      - TypeSynonymInstances
      - UndecidableInstances
      - UndecidableSuperClasses
      - ViewPatterns
    ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Wnoncanonical-monad-instances
      - -Wnoncanonical-monadfail-instances
    dependencies:
        - base >= 4.12
        - random
        - template-haskell
        - transformers
        - hashable
        - constraints
        - witness >= 0.4
    exposed-modules:
        - Data.Type.Heterogeneous
        - Data.OpenWitness
        - Data.OpenWitness.TypeRep
        - Data.OpenWitness.Typeable
        - Data.OpenWitness.Dynamic
        - Data.OpenWitness.Exception
        - Data.OpenWitness.ST
        - Data.OpenWitness.Instance
        - Data.OpenWitness.Witnessed

tests:
    tests:
        source-dirs: test
        default-extensions:
            - RankNTypes
            - EmptyDataDecls
            - GeneralizedNewtypeDeriving
            - ScopedTypeVariables
            - GADTs
            - FlexibleContexts
            - MultiParamTypeClasses
            - TemplateHaskell
        dependencies:
            - base >= 4.12
            - mtl
            - witness
            - open-witness
            - tasty
            - tasty-hunit
        main: Main.hs
        other-modules:
            - Object
